CREATE EXTENSION IF NOT EXISTS pgcrypto;

/*
 * Vizu - Identidade
 * Banco exclusivo do microsserviço identidade.
 * Não são permitidas FKs para bancos de outros serviços.
 */

CREATE SCHEMA IF NOT EXISTS identidade;
SET search_path TO identidade, public;

/* Lookups: valores evolutivos/configuráveis. */

CREATE TABLE perfil_plataforma_tipo
(
    perfil_plataforma_tipo_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                     VARCHAR(50)  NOT NULL UNIQUE,
    nome                       VARCHAR(100) NOT NULL,
    descricao                  TEXT,
    ativo                      BOOLEAN      NOT NULL DEFAULT TRUE,
    ordem                      SMALLINT     NOT NULL DEFAULT 0,
    criado_em                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em              TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE provedor_identidade
(
    provedor_identidade_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo                 VARCHAR(50)  NOT NULL UNIQUE,
    nome                   VARCHAR(100) NOT NULL,
    descricao              TEXT,
    ativo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    ordem                  SMALLINT     NOT NULL DEFAULT 0,
    criado_em              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE status_chamado
(
    status_chamado_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo            VARCHAR(50)  NOT NULL UNIQUE,
    nome              VARCHAR(100) NOT NULL,
    descricao         TEXT,
    terminal          BOOLEAN      NOT NULL DEFAULT FALSE,
    ativo             BOOLEAN      NOT NULL DEFAULT TRUE,
    ordem             SMALLINT     NOT NULL DEFAULT 0,
    criado_em         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em     TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE categoria_chamado
(
    categoria_chamado_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo               VARCHAR(50)  NOT NULL UNIQUE,
    nome                 VARCHAR(100) NOT NULL,
    descricao            TEXT,
    ativo                BOOLEAN      NOT NULL DEFAULT TRUE,
    ordem                SMALLINT     NOT NULL DEFAULT 0,
    criado_em            TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em        TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

/* Equipe interna da Vizu: não pertence a tenant ou loja. */

CREATE TABLE usuario_plataforma
(
    usuario_plataforma_id     UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    perfil_plataforma_tipo_id SMALLINT     NOT NULL REFERENCES perfil_plataforma_tipo,
    nome                      TEXT         NOT NULL,
    email                     TEXT         NOT NULL,
    senha_hash                TEXT         NOT NULL,
    senha_temporaria          BOOLEAN      NOT NULL DEFAULT TRUE,
    mfa_habilitado            BOOLEAN      NOT NULL DEFAULT FALSE,
    ativo                     BOOLEAN      NOT NULL DEFAULT TRUE,
    ultimo_login_em           TIMESTAMPTZ,
    criado_em                 TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em             TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX uq_usuario_plataforma_email
    ON usuario_plataforma (LOWER(email));

/* Tenant e lojas. */

CREATE TABLE contratante
(
    contratante_id                    UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    nome_fantasia                     TEXT         NOT NULL,
    razao_social                      TEXT         NOT NULL,
    cnpj                              VARCHAR(14)  NOT NULL UNIQUE,
    telefone_responsavel              TEXT         NOT NULL,
    inscricao_estadual                TEXT,
    timezone                          VARCHAR(50)  NOT NULL DEFAULT 'America/Sao_Paulo',
    dia_vencimento                    SMALLINT     NOT NULL CHECK (dia_vencimento IN (5, 15, 25)),
    pagamento_ate                     TIMESTAMPTZ  NOT NULL,
    pacote_estorno_tipo               VARCHAR(20)  NOT NULL DEFAULT 'AUTOMATICO'
        CHECK (pacote_estorno_tipo IN ('AUTOMATICO', 'MANUAL')),
    pacote_estorno_antecedencia_horas INTEGER      NOT NULL DEFAULT 2
        CHECK (pacote_estorno_antecedencia_horas >= 0),
    feedback_ativo                    BOOLEAN      NOT NULL DEFAULT TRUE,
    feedback_atraso_minutos           INTEGER      NOT NULL DEFAULT 90
        CHECK (feedback_atraso_minutos BETWEEN 15 AND 1440),
    ativo                             BOOLEAN      NOT NULL DEFAULT TRUE,
    suspenso_em                       TIMESTAMPTZ,
    suspenso_por                      UUID REFERENCES usuario_plataforma,
    motivo_suspensao                  TEXT,
    criado_em                         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em                     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_contratante_suspensao
        CHECK ((suspenso_em IS NULL AND suspenso_por IS NULL) OR suspenso_em IS NOT NULL)
);

CREATE TABLE configuracao_plataforma
(
    configuracao_plataforma_id UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id             UUID         NOT NULL UNIQUE REFERENCES contratante ON DELETE CASCADE,
    nome                       TEXT         NOT NULL,
    slogan                     TEXT,
    hero_titulo                VARCHAR(160),
    hero_palavra_gradiente     VARCHAR(80),
    cor_primaria               VARCHAR(7)   NOT NULL DEFAULT '#2E5BFF',
    cor_secundaria             VARCHAR(7)   NOT NULL DEFAULT '#8B5CF6',
    cor_topbar                 VARCHAR(7)   NOT NULL DEFAULT '#FFFFFF',
    modo_escuro                BOOLEAN      NOT NULL DEFAULT FALSE,
    dominio                    VARCHAR(255),
    subdominio                 VARCHAR(63)  NOT NULL,
    arquivo_logo_id            UUID,
    arquivo_icone_id           UUID,
    arquivo_capa_id            UUID,
    confirmar_auto_presencial  BOOLEAN      NOT NULL DEFAULT FALSE,
    confirmar_auto_online      BOOLEAN      NOT NULL DEFAULT FALSE,
    criado_em                  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_config_cor_primaria CHECK (cor_primaria ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_config_cor_secundaria CHECK (cor_secundaria ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT ck_config_cor_topbar CHECK (cor_topbar ~ '^#[0-9A-Fa-f]{6}$')
);

CREATE UNIQUE INDEX uq_configuracao_subdominio
    ON configuracao_plataforma (LOWER(subdominio));

CREATE UNIQUE INDEX uq_configuracao_dominio
    ON configuracao_plataforma (LOWER(dominio))
    WHERE dominio IS NOT NULL;

CREATE TABLE loja
(
    loja_id                UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id         UUID         NOT NULL REFERENCES contratante,
    nome                   TEXT         NOT NULL,
    telefone               TEXT         NOT NULL,
    logradouro             TEXT         NOT NULL,
    numero                 TEXT         NOT NULL,
    complemento            TEXT,
    bairro                 TEXT         NOT NULL,
    cidade                 TEXT         NOT NULL,
    estado                 CHAR(2)      NOT NULL,
    cep                    VARCHAR(8)   NOT NULL,
    capacidade_simultanea  INTEGER      NOT NULL CHECK (capacidade_simultanea > 0),
    ativo                  BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em              TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_loja_id_contratante UNIQUE (loja_id, contratante_id),
    CONSTRAINT uq_loja_nome_contratante UNIQUE (contratante_id, nome)
);

CREATE INDEX idx_loja_contratante_ativo ON loja (contratante_id, ativo);

/* Usuários e autenticação. */

CREATE TABLE usuario
(
    usuario_id            UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id        UUID         NOT NULL REFERENCES contratante,
    nome                  TEXT         NOT NULL,
    email                 TEXT,
    telefone              TEXT,
    cpf                   VARCHAR(11),
    ativo                 BOOLEAN      NOT NULL DEFAULT TRUE,
    recebe_notificacao    BOOLEAN      NOT NULL DEFAULT TRUE,
    authz_version         INTEGER      NOT NULL DEFAULT 1 CHECK (authz_version > 0),
    ultimo_login_em       TIMESTAMPTZ,
    criado_em             TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em         TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_usuario_id_contratante UNIQUE (usuario_id, contratante_id),
    CONSTRAINT ck_usuario_identificador CHECK (email IS NOT NULL OR telefone IS NOT NULL)
);

CREATE UNIQUE INDEX uq_usuario_email_contratante
    ON usuario (contratante_id, LOWER(email))
    WHERE email IS NOT NULL;

CREATE UNIQUE INDEX uq_usuario_telefone_contratante
    ON usuario (contratante_id, telefone)
    WHERE telefone IS NOT NULL;

CREATE UNIQUE INDEX uq_usuario_cpf_contratante
    ON usuario (contratante_id, cpf)
    WHERE cpf IS NOT NULL;

CREATE TABLE usuario_loja
(
    usuario_id      UUID        NOT NULL,
    loja_id         UUID        NOT NULL,
    contratante_id  UUID        NOT NULL,
    loja_padrao     BOOLEAN     NOT NULL DEFAULT FALSE,
    criado_em       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usuario_id, loja_id),
    FOREIGN KEY (usuario_id, contratante_id) REFERENCES usuario (usuario_id, contratante_id) ON DELETE CASCADE,
    FOREIGN KEY (loja_id, contratante_id) REFERENCES loja (loja_id, contratante_id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_usuario_loja_padrao
    ON usuario_loja (usuario_id)
    WHERE loja_padrao;

CREATE TABLE credencial_local
(
    usuario_id       UUID        NOT NULL PRIMARY KEY REFERENCES usuario ON DELETE CASCADE,
    senha_hash       TEXT        NOT NULL,
    senha_temporaria BOOLEAN     NOT NULL DEFAULT FALSE,
    alterada_em      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    criado_em        TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE identidade_externa
(
    identidade_externa_id  UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario_id              UUID        NOT NULL REFERENCES usuario ON DELETE CASCADE,
    provedor_identidade_id  SMALLINT    NOT NULL REFERENCES provedor_identidade,
    subject_externo         TEXT        NOT NULL,
    email_provedor          TEXT,
    criado_em               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (provedor_identidade_id, subject_externo),
    UNIQUE (usuario_id, provedor_identidade_id)
);

CREATE TABLE sessao_refresh_token
(
    sessao_refresh_token_id UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario_id              UUID        NOT NULL REFERENCES usuario ON DELETE CASCADE,
    familia_id              UUID        NOT NULL,
    token_hash              CHAR(64)    NOT NULL UNIQUE,
    emitido_em              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expira_em               TIMESTAMPTZ NOT NULL,
    revogado_em             TIMESTAMPTZ,
    substituido_por_hash    CHAR(64),
    ip_origem               INET,
    user_agent              TEXT,
    CHECK (expira_em > emitido_em)
);

CREATE INDEX idx_sessao_usuario_ativa
    ON sessao_refresh_token (usuario_id, expira_em)
    WHERE revogado_em IS NULL;

CREATE TABLE historico_senha
(
    historico_senha_id UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario_id         UUID        NOT NULL REFERENCES usuario ON DELETE CASCADE,
    senha_hash         TEXT        NOT NULL,
    criado_em          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_historico_senha_usuario
    ON historico_senha (usuario_id, criado_em DESC);

/* RBAC e concessões excepcionais. */

CREATE TABLE acesso
(
    acesso_id  UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    codigo     VARCHAR(150) NOT NULL UNIQUE,
    descricao TEXT         NOT NULL,
    ativo     BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE perfil_plataforma_acesso
(
    perfil_plataforma_tipo_id SMALLINT NOT NULL REFERENCES perfil_plataforma_tipo ON DELETE CASCADE,
    acesso_id                 UUID     NOT NULL REFERENCES acesso,
    PRIMARY KEY (perfil_plataforma_tipo_id, acesso_id)
);

CREATE TABLE perfil
(
    perfil_id      UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id UUID REFERENCES contratante,
    nome           VARCHAR(100) NOT NULL,
    descricao      TEXT         NOT NULL,
    sistema        BOOLEAN      NOT NULL DEFAULT FALSE,
    ativo          BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT ck_perfil_sistema CHECK ((contratante_id IS NULL) = sistema)
);

CREATE UNIQUE INDEX uq_perfil_sistema_nome
    ON perfil (LOWER(nome)) WHERE contratante_id IS NULL;

CREATE UNIQUE INDEX uq_perfil_tenant_nome
    ON perfil (contratante_id, LOWER(nome)) WHERE contratante_id IS NOT NULL;

CREATE TABLE perfil_acesso
(
    perfil_id UUID NOT NULL REFERENCES perfil ON DELETE CASCADE,
    acesso_id UUID NOT NULL REFERENCES acesso,
    PRIMARY KEY (perfil_id, acesso_id)
);

CREATE TABLE usuario_perfil
(
    usuario_id UUID        NOT NULL REFERENCES usuario ON DELETE CASCADE,
    perfil_id  UUID        NOT NULL REFERENCES perfil ON DELETE CASCADE,
    criado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usuario_id, perfil_id)
);

CREATE TABLE acesso_usuario
(
    usuario_id UUID        NOT NULL REFERENCES usuario ON DELETE CASCADE,
    acesso_id  UUID        NOT NULL REFERENCES acesso,
    criado_em  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (usuario_id, acesso_id)
);

/* Pessoas do negócio. Funcionário/cliente podem existir sem login. */

CREATE TABLE funcionario
(
    funcionario_id      UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id      UUID         NOT NULL REFERENCES contratante,
    usuario_id          UUID,
    nome                TEXT         NOT NULL,
    foto_arquivo_id     UUID,
    comissao_percentual NUMERIC(5,2) NOT NULL DEFAULT 0 CHECK (comissao_percentual BETWEEN 0 AND 100),
    bio                 TEXT,
    exibir_no_site      BOOLEAN      NOT NULL DEFAULT TRUE,
    ativo               BOOLEAN      NOT NULL DEFAULT TRUE,
    criado_em           TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    atualizado_em       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_funcionario_id_contratante UNIQUE (funcionario_id, contratante_id),
    CONSTRAINT uq_funcionario_usuario UNIQUE (usuario_id),
    FOREIGN KEY (usuario_id, contratante_id) REFERENCES usuario (usuario_id, contratante_id)
);

CREATE INDEX idx_funcionario_contratante_ativo
    ON funcionario (contratante_id, ativo);

CREATE TABLE funcionario_loja
(
    funcionario_id UUID        NOT NULL,
    loja_id        UUID        NOT NULL,
    contratante_id UUID        NOT NULL,
    ativo          BOOLEAN     NOT NULL DEFAULT TRUE,
    criado_em      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (funcionario_id, loja_id),
    FOREIGN KEY (funcionario_id, contratante_id)
        REFERENCES funcionario (funcionario_id, contratante_id) ON DELETE CASCADE,
    FOREIGN KEY (loja_id, contratante_id)
        REFERENCES loja (loja_id, contratante_id) ON DELETE CASCADE
);

CREATE TABLE funcionario_portfolio
(
    funcionario_portfolio_id UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    funcionario_id           UUID        NOT NULL REFERENCES funcionario ON DELETE CASCADE,
    arquivo_id               UUID        NOT NULL,
    posicao                  INTEGER     NOT NULL DEFAULT 0 CHECK (posicao >= 0),
    criado_em                TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (funcionario_id, arquivo_id)
);

CREATE INDEX idx_funcionario_portfolio_ordem
    ON funcionario_portfolio (funcionario_id, posicao);

CREATE TABLE cliente
(
    cliente_id      UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id  UUID        NOT NULL REFERENCES contratante,
    usuario_id      UUID,
    nome            TEXT        NOT NULL,
    telefone        TEXT        NOT NULL,
    email           TEXT,
    ativo           BOOLEAN     NOT NULL DEFAULT TRUE,
    criado_em       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    atualizado_em   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_cliente_id_contratante UNIQUE (cliente_id, contratante_id),
    CONSTRAINT uq_cliente_usuario UNIQUE (usuario_id),
    CONSTRAINT uq_cliente_telefone_contratante UNIQUE (contratante_id, telefone),
    FOREIGN KEY (usuario_id, contratante_id) REFERENCES usuario (usuario_id, contratante_id)
);

CREATE INDEX idx_cliente_contratante_nome
    ON cliente (contratante_id, LOWER(nome));

/* Configuração global, suporte e auditoria. */

CREATE TABLE configuracao_global
(
    chave                         VARCHAR(100) NOT NULL PRIMARY KEY,
    valor                         TEXT         NOT NULL,
    usuario_plataforma_atualizador_id UUID     NOT NULL REFERENCES usuario_plataforma,
    atualizado_em                 TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE impersonacao
(
    impersonacao_id       UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    usuario_plataforma_id UUID        NOT NULL REFERENCES usuario_plataforma,
    contratante_id        UUID        NOT NULL REFERENCES contratante,
    usuario_id            UUID        NOT NULL REFERENCES usuario,
    motivo                TEXT        NOT NULL,
    iniciado_em           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expira_em             TIMESTAMPTZ NOT NULL,
    finalizado_em         TIMESTAMPTZ,
    ip_origem             INET,
    user_agent            TEXT,
    FOREIGN KEY (usuario_id, contratante_id)
        REFERENCES usuario (usuario_id, contratante_id),
    CHECK (expira_em > iniciado_em),
    CHECK (finalizado_em IS NULL OR finalizado_em >= iniciado_em)
);

CREATE INDEX idx_impersonacao_tenant_data
    ON impersonacao (contratante_id, iniciado_em DESC);

CREATE TABLE chamado
(
    chamado_id           UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    contratante_id       UUID        NOT NULL REFERENCES contratante,
    loja_id              UUID,
    usuario_solicitante_id UUID      NOT NULL REFERENCES usuario,
    categoria_chamado_id SMALLINT    NOT NULL REFERENCES categoria_chamado,
    status_chamado_id    SMALLINT    NOT NULL REFERENCES status_chamado,
    assunto              VARCHAR(160) NOT NULL,
    descricao            TEXT        NOT NULL,
    iniciado_em          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    finalizado_em        TIMESTAMPTZ,
    atualizado_em        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    FOREIGN KEY (loja_id, contratante_id) REFERENCES loja (loja_id, contratante_id),
    FOREIGN KEY (usuario_solicitante_id, contratante_id)
        REFERENCES usuario (usuario_id, contratante_id)
);

CREATE INDEX idx_chamado_tenant_status
    ON chamado (contratante_id, status_chamado_id, iniciado_em DESC);

CREATE TABLE comentario_chamado
(
    comentario_chamado_id UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    chamado_id            UUID        NOT NULL REFERENCES chamado ON DELETE CASCADE,
    autor_tipo            VARCHAR(20) NOT NULL CHECK (autor_tipo IN ('USUARIO', 'PLATAFORMA')),
    autor_id              UUID        NOT NULL,
    descricao             TEXT        NOT NULL,
    criado_em             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE anexo_chamado
(
    anexo_chamado_id UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    chamado_id       UUID        NOT NULL REFERENCES chamado ON DELETE CASCADE,
    arquivo_id       UUID        NOT NULL,
    enviado_por_tipo VARCHAR(20) NOT NULL CHECK (enviado_por_tipo IN ('USUARIO', 'PLATAFORMA')),
    enviado_por_id   UUID        NOT NULL,
    criado_em        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (chamado_id, arquivo_id)
);

CREATE TABLE audit_log
(
    audit_log_id    UUID        NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    ator_tipo       VARCHAR(20) NOT NULL CHECK (ator_tipo IN ('USUARIO', 'PLATAFORMA', 'SERVICO')),
    ator_id         UUID,
    contratante_id  UUID,
    acao            VARCHAR(150) NOT NULL,
    recurso_tipo    VARCHAR(100) NOT NULL,
    recurso_id      UUID,
    dados_antes     JSONB,
    dados_depois    JSONB,
    correlation_id  UUID,
    ip_origem       INET,
    user_agent      TEXT,
    criado_em       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_audit_tenant_data
    ON audit_log (contratante_id, criado_em DESC);

/* Entrega confiável de eventos. */

CREATE TABLE outbox_event
(
    event_id        UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    event_type      VARCHAR(150) NOT NULL,
    aggregate_type  VARCHAR(100) NOT NULL,
    aggregate_id    UUID         NOT NULL,
    contratante_id  UUID,
    loja_id         UUID,
    correlation_id  UUID,
    causation_id    UUID,
    payload          JSONB        NOT NULL,
    ocorrido_em      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    publicado_em     TIMESTAMPTZ,
    tentativas       INTEGER      NOT NULL DEFAULT 0 CHECK (tentativas >= 0),
    proxima_tentativa_em TIMESTAMPTZ,
    ultimo_erro      TEXT
);

CREATE INDEX idx_outbox_pendente
    ON outbox_event (ocorrido_em)
    WHERE publicado_em IS NULL;

CREATE TABLE inbox_event
(
    event_id       UUID         NOT NULL,
    consumer       VARCHAR(100) NOT NULL,
    event_type     VARCHAR(150) NOT NULL,
    recebido_em    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    processado_em  TIMESTAMPTZ,
    ultimo_erro    TEXT,
    PRIMARY KEY (event_id, consumer)
);
