SET search_path TO identidade, public;

INSERT INTO acesso (codigo, descricao)
VALUES
    ('identidade.contratante.visualizar', 'Visualizar dados cadastrais do contratante.'),
    ('identidade.contratante.editar', 'Editar dados cadastrais do contratante.'),
    ('identidade.contratante.suspender', 'Suspender um contratante.'),
    ('identidade.contratante.reativar', 'Reativar um contratante.'),
    ('identidade.configuracao_plataforma.editar', 'Editar branding e site do contratante.'),
    ('identidade.configuracao_global.editar', 'Editar configurações globais da plataforma.'),
    ('identidade.loja.criar', 'Cadastrar uma loja.'),
    ('identidade.loja.editar', 'Editar uma loja.'),
    ('identidade.loja.visualizar', 'Visualizar lojas.'),
    ('identidade.loja.desativar', 'Desativar uma loja.'),
    ('identidade.usuario.criar', 'Criar um usuário do contratante.'),
    ('identidade.usuario.editar', 'Editar outro usuário.'),
    ('identidade.usuario.visualizar', 'Visualizar outros usuários.'),
    ('identidade.usuario.desativar', 'Desativar outro usuário.'),
    ('identidade.usuario.redefinir_senha', 'Forçar redefinição de senha.'),
    ('identidade.funcionario.criar', 'Cadastrar um funcionário.'),
    ('identidade.funcionario.editar', 'Editar um funcionário.'),
    ('identidade.funcionario.visualizar', 'Visualizar funcionários.'),
    ('identidade.funcionario.desativar', 'Desativar um funcionário.'),
    ('identidade.funcionario.gerenciar_comissao', 'Editar comissão de funcionário.'),
    ('identidade.funcionario_portfolio.gerenciar', 'Gerenciar portfólio de funcionário.'),
    ('identidade.cliente.criar', 'Cadastrar cliente manualmente.'),
    ('identidade.cliente.editar', 'Editar cliente.'),
    ('identidade.cliente.visualizar', 'Visualizar clientes.'),
    ('identidade.cliente.desativar', 'Desativar cliente.'),
    ('identidade.acesso.gerenciar', 'Gerenciar catálogo de acessos.'),
    ('identidade.perfil.gerenciar', 'Gerenciar perfis e atribuições.'),
    ('identidade.impersonacao.iniciar', 'Iniciar impersonação.'),
    ('identidade.impersonacao.visualizar_log', 'Visualizar logs de impersonação.'),
    ('identidade.historico_senha.visualizar', 'Visualizar histórico de senhas.'),
    ('identidade.chamado.abrir', 'Abrir chamado de suporte.'),
    ('identidade.chamado.visualizar', 'Visualizar chamados do próprio contratante.'),
    ('identidade.chamado.visualizar_todos', 'Visualizar chamados de todos os contratantes.'),
    ('identidade.chamado.responder', 'Responder chamado.'),
    ('identidade.chamado.fechar', 'Fechar chamado.'),
    ('identidade.categoria_chamado.gerenciar', 'Gerenciar categorias de chamado.'),
    ('agendamento.loja_horario.gerenciar', 'Gerenciar horários de funcionamento.'),
    ('agendamento.funcionario_horario.gerenciar', 'Gerenciar horários de funcionário.'),
    ('agendamento.bloqueio_agenda.gerenciar', 'Gerenciar bloqueios de agenda.'),
    ('agendamento.servico.criar', 'Cadastrar serviço.'),
    ('agendamento.servico.editar', 'Editar serviço.'),
    ('agendamento.servico.visualizar', 'Visualizar catálogo de serviços.'),
    ('agendamento.servico.desativar', 'Desativar serviço.'),
    ('agendamento.funcionario_servico.gerenciar', 'Associar funcionários e serviços.'),
    ('agendamento.pacote.criar', 'Criar pacote.'),
    ('agendamento.pacote.editar', 'Editar pacote.'),
    ('agendamento.pacote.visualizar', 'Visualizar pacotes.'),
    ('agendamento.pacote.desativar', 'Desativar pacote.'),
    ('agendamento.cliente_pacote.vender', 'Vender pacote para cliente.'),
    ('agendamento.cliente_pacote.visualizar', 'Visualizar pacotes de clientes.'),
    ('agendamento.cliente_pacote.cancelar', 'Cancelar pacote de cliente.'),
    ('agendamento.forma_pagamento.gerenciar', 'Gerenciar formas de pagamento.'),
    ('agendamento.agendamento.criar', 'Criar agendamento.'),
    ('agendamento.agendamento.visualizar', 'Visualizar agenda da loja.'),
    ('agendamento.agendamento.editar', 'Editar agendamento.'),
    ('agendamento.agendamento.confirmar', 'Confirmar agendamento.'),
    ('agendamento.agendamento.remarcar', 'Remarcar agendamento.'),
    ('agendamento.agendamento.cancelar', 'Cancelar agendamento.'),
    ('agendamento.agendamento.finalizar', 'Finalizar atendimento.'),
    ('agendamento.agendamento.aplicar_desconto', 'Aplicar desconto.'),
    ('agendamento.pagamento.registrar', 'Registrar pagamento.'),
    ('agendamento.pagamento.visualizar', 'Visualizar pagamentos.'),
    ('agendamento.historico_pagamento.visualizar', 'Visualizar auditoria financeira.'),
    ('agendamento.relatorio_financeiro.visualizar', 'Visualizar relatórios financeiros.'),
    ('agendamento.avaliacao.visualizar', 'Visualizar avaliações.'),
    ('agendamento.avaliacao.moderar', 'Moderar avaliações.'),
    ('notificacao.modelo_whatsapp.gerenciar', 'Gerenciar modelos de WhatsApp.'),
    ('notificacao.instancia_whatsapp.gerenciar', 'Gerenciar instâncias na Evolution API.'),
    ('notificacao.historico.visualizar', 'Visualizar histórico de notificações.'),
    ('notificacao.notificacao.enviar_manual', 'Enviar notificação manual.'),
    ('notificacao.notificacao.visualizar_todas', 'Visualizar notificações de terceiros.'),
    ('upload.arquivo.enviar', 'Enviar arquivo.'),
    ('upload.arquivo.visualizar', 'Visualizar arquivos de terceiros.'),
    ('upload.arquivo.excluir', 'Excluir arquivo.'),
    ('upload.arquivo_log.visualizar', 'Visualizar auditoria de arquivos.')
ON CONFLICT (codigo) DO UPDATE SET
    descricao = EXCLUDED.descricao,
    ativo = TRUE,
    atualizado_em = NOW();
